const DBimg = {
    divan_lira: new URL('./divan_lira.jpg', import.meta.url).href,
    divan_lira1: new URL('./divan_lira1.jpg', import.meta.url).href,
    kreslo_florentsiya: new URL('./kreslo_florentsiya.jpg', import.meta.url).href,
    kreslo_florentsiya1: new URL('./kreslo_florentsiya1.jpg', import.meta.url).href,
    kreslo_florentsiya2: new URL('./kreslo_florentsiya2.jpg', import.meta.url).href,
    kreslo: new URL('./kreslo.jpg', import.meta.url).href,
    kreslo1: new URL('./kreslo1.jpg', import.meta.url).href,
    kreslo2: new URL('./kreslo2.jpg', import.meta.url).href,
    lamp_arkadiya: new URL('./lamp_arkadiya.jpg', import.meta.url).href,
    lamp_arkadiya1: new URL('./lamp_arkadiya1.jpg', import.meta.url).href,
    lamp: new URL('./lamp.jpg', import.meta.url).href,
    lamp1: new URL('./lamp1.jpg', import.meta.url).href,
    puf_rozaliya: new URL('./puf_rozaliya.jpg', import.meta.url).href,
    puf_rozaliya1: new URL('./puf_rozaliya1.jpg', import.meta.url).href,
    puf: new URL('./puf.jpg', import.meta.url).href,
    puf1: new URL('./puf1.jpg', import.meta.url).href,
    stol_lolo: new URL('./stol_lolo.jpg', import.meta.url).href,
    stol_lolo2: new URL('./stol_lolo2.jpg', import.meta.url).href,
    stol_lolo3: new URL('./stol_lolo3.jpg', import.meta.url).href,
    stol_versal: new URL('./stol_versal.jpg', import.meta.url).href,
    stol_versal1: new URL('./stol_versal1.jpg', import.meta.url).href,
    stol_versal2: new URL('./stol_versal2.jpg', import.meta.url).href,
    stul_ameliya: new URL('./stul_ameliya.jpg', import.meta.url).href,
    stul_ameliya1: new URL('./stul_ameliya1.jpg', import.meta.url).href,
    stul_ameliya3: new URL('./stul_ameliya3.jpg', import.meta.url).href,
}

export default DBimg;